# Generated by Django 3.1.4 on 2021-02-01 13:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Регистрационный номер')),
                ('name', models.CharField(max_length=50, verbose_name='Кличка')),
                ('age', models.SmallIntegerField(null=True, verbose_name='Возраст')),
                ('type_of_animal', models.CharField(choices=[(None, 'Вид животного'), ('Собака', 'Собака'), ('Кот', 'Кот'), ('Попугай', 'Попугай')], max_length=12, null=True, verbose_name='Вид животного')),
                ('color', models.CharField(choices=[(None, 'Выберите окрас'), ('Черный', 'Черный'), ('Белый', 'Белый'), ('Серый', 'Серый'), ('Рыжий', 'Рыжий'), ('Коричневый', 'Коричневый'), ('Пестрый', 'Пестрый'), ('Желтый', 'Желтый'), ('Зеленый', 'Зеленый'), ('Голубой', 'Голубой')], max_length=12, null=True, verbose_name='Окрас')),
                ('data', models.DateField(auto_now_add=True, null=True, verbose_name='Дата поступления')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('foto', models.ImageField(blank=True, upload_to='foto_pet', verbose_name='Фото')),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.breed', verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'питомец',
                'verbose_name_plural': 'Питомцы',
                'ordering': ['name'],
            },
        ),
    ]
