# Generated by Django 3.1.4 on 2021-02-01 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20210201_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Регистрационный номер'),
        ),
    ]
